# Generated by Django 4.2.3 on 2023-07-19 19:46

import backend.account.utils
import backend.account.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[backend.account.validators.validate_email],
                        verbose_name="Email address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=255, verbose_name="Paydalaniwshinin' ati"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=255, verbose_name="Paydalaniwshinin' familiyasi"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        max_length=255, verbose_name="Paydalaniwshinin a'kesinin' ati"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            backend.account.validators.validate_uzb_phone_number
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("A'YEL", "A'yel"), ("ERKEK", "Erkek")], max_length=10
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[backend.account.utils.validate_age],
                        verbose_name="Tuwilg'an kuni",
                    ),
                ),
                (
                    "face",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        null=True,
                        quality=100,
                        scale=1.0,
                        size=[1920, 1080],
                        upload_to="faces/",
                        verbose_name="Insannin' ju'zi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PAYDALANIWSHI", "Paydalaniwshi"),
                            ("ADMINISTRATOR", "Administrator"),
                        ],
                        default="PAYDALANIWSHI",
                        max_length=15,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="Tasdiyiqlaw ushin 6 xanali san",
                    ),
                ),
                (
                    "is_human",
                    models.BooleanField(
                        default=False,
                        verbose_name="Eger insannin' ju'zi bolsa haqiqiy insan.",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounts",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("avatar", models.ImageField(blank=True, upload_to="avatars/")),
                (
                    "bio",
                    models.TextField(
                        max_length=1000, verbose_name="Ozi haqqida mag'liwmat"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UYLENBEGEN", "UYLENBEGEN"),
                            ("TURMISQA SHIQPAG'AN", "TURMISQA SHIQPAG'AN"),
                            ("AJRASQAN", "AJRASQAN"),
                            ("BOS EMES", "BOS EMES"),
                            ("BAXTIN TAPQAN", "BAXTIN TAPQAN"),
                        ],
                        max_length=25,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("JUMIS", "JUMIS"),
                            ("JUMISSIZ", "JUMISSIZ"),
                            ("STUDENT", "STUDENT"),
                            ("BASQA", "BASQA"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "hobbies",
                    models.ManyToManyField(
                        related_name="hobby_of_user", to="account.hobby"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=100,
                        scale=1.0,
                        size=[1920, 1080],
                        upload_to="images/",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        max_length=255, verbose_name="Image haqida qisqasha mag'liwmat"
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
